local _, SMK = ...

-- note 是 ICON_NOTES 中的稳定国际化键，用于图标的鼠标提示。
-- 正数 ID 固定表示 Atlas。
SMK.AtlasTextures = {
    { id = 1, atlas = "AllianceSymbol", note = "alliance" },
    { id = 2, atlas = "HordeSymbol", note = "horde" },
    { id = 3, atlas = "GreatVault-32x32", note = "great_vault" },
    { id = 4, atlas = "pvpqueue-sidebar-honorbar-badge-horde", note = "horde_icon" },
    { id = 5, atlas = "pvpqueue-sidebar-honorbar-badge-alliance", note = "alliance_icon" },
    { id = 6, atlas = "Banker", note = "bank" },
    { id = 7, atlas = "Auctioneer", note = "auction_house" },
    { id = 8, atlas = "Mailbox", note = "mailbox" },
    { id = 9, atlas = "Innkeeper", note = "innkeeper" },
    { id = 10, atlas = "FlightMaster", note = "flight_master" },
    { id = 11, atlas = "StableMaster", note = "stable_master" },
    { id = 12, atlas = "Barbershop-32x32", note = "barber" },
    { id = 13, atlas = "poi-transmogrifier", note = "transmogrifier" },
    { id = 14, atlas = "trading-post-minimap-icon", note = "trading_post" },
    { id = 15, atlas = "SpellIcon-256x256-SellJunk", note = "merchant" },
    { id = 16, atlas = "Class", note = "class_trainer" },
    { id = 17, atlas = "Profession", note = "profession_trainer" },
    { id = 18, atlas = "Professions-Crafting-Orders-Icon", note = "crafting_orders" },
    { id = 19, atlas = "TimewalkingVendor-32x32", note = "timewalking_vendor" },
    { id = 20, atlas = "UpgradeItem-32x32", note = "item_upgrade" },
    { id = 21, atlas = "MagePortalAlliance", note = "alliance_portal" },
    { id = 22, atlas = "MagePortalHorde", note = "horde_portal" },
    { id = 23, atlas = "TaxiNode_Continent_Alliance", note = "alliance_portal_alt" },
    { id = 24, atlas = "TaxiNode_Continent_Horde", note = "horde_portal_alt" },
    { id = 25, atlas = "QuestNormal", note = "quest" },
    { id = 26, atlas = "HordeAssaultsMapBanner", note = "alliance_pvp" },
    { id = 27, atlas = "AllianceAssaultsMapBanner", note = "horde_pvp" },
    { id = 28, atlas = "Waypoint-MapPin-Minimap-Tracked", note = "coordinate_selected" },
    { id = 29, atlas = "Waypoint-MapPin-Minimap-Untracked", note = "coordinate_unselected" },
    { id = 30, atlas = "Raid", note = "raid" },
    { id = 31, atlas = "Dungeon", note = "dungeon" },
    { id = 32, atlas = "delves-bountiful", note = "delve" },
    { id = 33, atlas = "vignettekillboss-SuperTracked", note = "rare_creature" },
    { id = 34, atlas = "VignetteLoot", note = "treasure" },
    { id = 35, atlas = "TaxiNode_Continent_Neutral", note = "portal" },
    { id = 36, atlas = "FlightMasterArgus", note = "teleport_beacon" },
    { id = 37, atlas = "CaveUnderground-Down", note = "cave_entrance" },
    { id = 38, atlas = "CaveUnderground-Up", note = "cave_exit" },
}
