local _, SMK = ...

-- note 仅供开发者维护时识别用途，不在用户界面中显示。
-- 正数 ID 固定表示 Atlas。
SMK.AtlasTextures = {
    { id = 1, atlas = "AllianceSymbol", note = "联盟" },
    { id = 2, atlas = "HordeSymbol", note = "部落" },
    { id = 3, atlas = "GreatVault-32x32", note = "宝库" },
    { id = 4, atlas = "pvpqueue-sidebar-honorbar-badge-horde", note = "部落图标" },
    { id = 5, atlas = "pvpqueue-sidebar-honorbar-badge-alliance", note = "联盟图标" },
    { id = 6, atlas = "Banker", note = "银行" },
    { id = 7, atlas = "Auctioneer", note = "拍卖" },
    { id = 8, atlas = "Mailbox", note = "邮箱" },
    { id = 9, atlas = "Innkeeper", note = "旅店" },
    { id = 10, atlas = "FlightMaster", note = "飞行管理员" },
    { id = 11, atlas = "StableMaster", note = "兽栏管理员" },
    { id = 12, atlas = "Barbershop-32x32", note = "理发师" },
    { id = 13, atlas = "poi-transmogrifier", note = "幻化师" },
    { id = 14, atlas = "trading-post-minimap-icon", note = "商栈" },
    { id = 15, atlas = "SpellIcon-256x256-SellJunk", note = "商人" },
    { id = 16, atlas = "Class", note = "职业训练师" },
    { id = 17, atlas = "Profession", note = "专业训练师" },
    { id = 18, atlas = "Waypoint-MapPin-Minimap-Tracked", note = "其他" },
    { id = 19, atlas = "Professions-Crafting-Orders-Icon", note = "订单" },
    { id = 20, atlas = "TimewalkingVendor-32x32", note = "漫游商人" },
    { id = 21, atlas = "UpgradeItem-32x32", note = "物品升级" },
    { id = 22, atlas = "MagePortalAlliance", note = "联盟传送门" },
    { id = 23, atlas = "MagePortalHorde", note = "部落传送门" },
    { id = 24, atlas = "ChromieTime-32x32", note = "克罗米" },
    { id = 25, atlas = "TaxiNode_Continent_Alliance", note = "联盟传送门2" },
    { id = 26, atlas = "TaxiNode_Continent_Horde", note = "部落传送门2" },
    { id = 27, atlas = "QuestNormal", note = "任务" },
    { id = 28, atlas = "HordeAssaultsMapBanner", note = "联盟PVP" },
    { id = 29, atlas = "AllianceAssaultsMapBanner", note = "部落PVP" },
    { id = 30, atlas = "Waypoint-MapPin-Minimap-Tracked", note = "坐标选中" },
    { id = 31, atlas = "Waypoint-MapPin-Minimap-Untracked", note = "坐标未选中" },
    { id = 32, atlas = "Class", note = "职业" },
    { id = 33, atlas = "Profession", note = "专业" },
    { id = 34, atlas = "Raid", note = "团队副本" },
    { id = 35, atlas = "Dungeon", note = "地下城" },
    { id = 36, atlas = "delves-bountiful", note = "地下堡" },
    { id = 37, atlas = "vignettekillboss-SuperTracked", note = "稀有怪物" },
    { id = 38, atlas = "VignetteLoot", note = "宝箱" },
    { id = 39, atlas = "TaxiNode_Continent_Neutral", note = "传送门" },
    { id = 40, atlas = "FlightMasterArgus", note = "传送道标" },
    { id = 41, atlas = "CaveUnderground-Down", note = "山洞进" },
    { id = 42, atlas = "CaveUnderground-Up", note = "山洞出" },
}
